[package]
name = "second"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = {version = "4.9.0"}
tokio = {version = "1.42.0", features = ["full"]}
anyhow = {version = "1.0.94"}
async-trait = { version = "0.1.83"}
